### ISSUE TITLE
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.

### ISSUE THREAD

**Issue by calboru** [torusresearch/openlogin-expo-sdk#16]
![Screen Shot 2022-05-24 at 2 39 08 PM](https://user-images.githubusercontent.com/26364385/170108615-fc65276f-283f-464b-af00-e5fcd0a72fb6.png)

**Comment by michaellee8** [comment]
This API will no longer be used in the soon released version.
